# Generated by Django 4.2.7 on 2023-11-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MbogaApp', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='white', max_length=100),
        ),
    ]
